//! Seed inputs for the mutational stress suite: valid REPL snippets spanning the
//! supported feature surface, for the mutator (see stress_test.zig) to perturb.
//! Breadth over depth -- every distinct construct is a seed it can splice.

/// Single-line expressions and declarations.
pub const lines = [_][]const u8{
    "1 + 2 * 3 - 4",
    "@as(u8, 255) + 1",
    "@as(i8, -128) - 1",
    "1 << 63",
    "0xffff_ffff_ffff_ffff",
    "@as(u4, 15) *% 2",
    "10 / 3",
    "10 % 3",
    "3.14 * 2.0",
    "@as(f32, 1.5) + @as(f32, 2.5)",
    "1e10",
    "-0.0",
    "~@as(u8, 0)",
    "5 & 3 | 8 ^ 1",
    "true and false or !true",
    "1 == 1 and 2 != 3",
    "@as(?u8, 5) orelse 0",
    "@as(?u8, null) orelse 42",
    "if (@as(?u8, 3)) |v| v else 0",
    "@as(u16, @intCast(@as(u8, 200)))",
    "@as(f64, @floatFromInt(7))",
    "@as(u8, @truncate(@as(u16, 300)))",
    "@intFromBool(true)",
    "@as(i32, @intFromFloat(3.9))",
    "@bitCast(@as(u32, 0x3f800000))",
    "blk: { const p: *const u32 = @ptrFromInt(0x1000); const q: *const u8 = @ptrCast(p); break :blk @intFromPtr(q); }",
    "blk: { const p: *const u32 = @ptrFromInt(0x1000); break :blk @intFromPtr(@constCast(p)); }",
    "blk: { const p: *volatile u32 = @ptrFromInt(0x1000); break :blk @intFromPtr(@volatileCast(p)); }",
    "blk: { const p: *u32 = @ptrFromInt(0x1000); break :blk @intFromPtr(@as(*align(4) u32, @alignCast(p))); }",
    "blk: { var arr = [_]u32{ 1, 2, 3 }; const s: []u32 = &arr; break :blk @as([]const u8, @ptrCast(s)).len; }",
    "[_]u8{ 1, 2, 3 }",
    "[_]u8{ 1, 2, 3 }.len",
    "\"hello world\"",
    "\"hi\"[0]",
    "blk: { const s: []const u8 = \"abcdef\"; break :blk s[1..4]; }",
    "@as([]const u8, \"xyz\").len",
    "[_]i32{ 5, 6, 7 } ++ [_]i32{ 8 }",
    "[_]u8{0} ** 4",
    "blk: { const S = struct { a: u8, b: u16 }; break :blk @as(S, .{ .a = 1, .b = 2 }).b; }",
    ".{ .x = 1, .y = 2 }",
    ".{ 1, 2, 3 }",
    "@sizeOf(struct { a: u64, b: u8 })",
    "blk: { const E = enum { a, b, c }; break :blk @intFromEnum(E.c); }",
    "blk: { const E = enum { north, south }; break :blk @tagName(E.south); }",
    "blk: { const U = union(enum) { n: u8, f: f32 }; break :blk @as(U, .{ .n = 7 }); }",
    "blk: { var s: u32 = 0; for (0..10) |i| s += i; break :blk s; }",
    "blk: { var n: u32 = 1; while (n < 100) n *= 2; break :blk n; }",
    "blk: { const x = 3; break :blk switch (x) { 1 => 10, 3 => 30, else => 0 }; }",
    "@typeName(u32)",
    "@typeInfo(u8).int.bits",
    "@min(3, 7, 1)",
    "@max(@as(u8, 4), 9)",
    "@popCount(@as(u8, 0b1011))",
    "@ctz(@as(u8, 8))",
    "@abs(@as(i32, -5))",
    "@errorName(error.Boom)",
    "@as(anyerror!u8, 5) catch 0",
    "@as(anyerror!u8, error.X) catch 0",
    "@import(\"builtin\").target.cpu.arch",
    "@TypeOf(@import(\"std\"))",
    "comptime { const x: u8 = 5; if (x != 5) unreachable; }",
    "blk: { var arr = [_]u8{ 1, 2, 3 }; break :blk arr[0..2]; }",
    "blk: { var x: u32 = 10; const p = &x; p.* += 5; break :blk x; }",
    "blk: { var buf: [4]u8 = undefined; @memset(&buf, 7); break :blk buf[2]; }",
    "blk: { var buf: [3]u8 = undefined; const src = [_]u8{ 7, 8, 9 }; @memcpy(&buf, &src); break :blk buf[1]; }",
    "blk: { const E = enum(u8) { a = 2, b, c = 10 }; break :blk @intFromEnum(E.b); }",
    "blk: { const e: anyerror!u8 = error.X; break :blk if (e) |v| v else |_| @as(u8, 99); }",
    "@reduce(.Xor, @as(@Vector(3, u8), .{ 1, 2, 4 }))",
    "blk: { const V = @Vector(4, u8); const a: V = @splat(2); break :blk @reduce(.Add, a); }",
    "@offsetOf(struct { a: u8, b: u64 }, \"b\")",
    "@FieldType(struct { x: bool, y: u16 }, \"y\")",
    "@bitOffsetOf(packed struct { a: u3, b: u5 }, \"b\")",
    "@as(u8, undefined)",
    "@Int(.unsigned, 8)",
    "blk: { const S = struct { fn f(comptime T: type, x: T) T { return x + 1; } }; break :blk S.f(u8, 41); }",
    "blk: { const S = struct { v: u8, fn get(self: @This()) u8 { return self.v; } }; const s = S{ .v = 7 }; break :blk s.get(); }",
    "blk: { var s: u32 = 0; outer: for (0..5) |i| { for (0..5) |j| { if (i * j > 6) break :outer; s += 1; } } break :blk s; }",
    "blk: { const E1 = error{A}; const E2 = error{B}; const E = E1 || E2; break :blk @errorName(@as(E, error.A)); }",
    "blk: { const s: [:0]const u8 = \"hi\"; break :blk s.len + s[s.len]; }",
    "blk: { const P = packed struct { a: u4, b: u4 }; const p = P{ .a = 3, .b = 5 }; break :blk @as(u8, @bitCast(p)); }",
    "blk: { var i: u8 = 0; const r = while (i < 3) : (i += 1) { if (i == 2) break i * 10; } else 99; break :blk r; }",
    "blk: { const m = [_][2]u8{ .{ 1, 2 }, .{ 3, 4 } }; break :blk m[1][0]; }",
    "blk: { const t = .{ @as(u8, 1), true, @as(f32, 2.5) }; break :blk t[0]; }",
    "@as(f16, 65504) + @as(f16, 65504)",
    "@as(u32, @bitCast(@as(f32, -0.0)))",
    "@sqrt(@as(f64, 2.0))",
};

/// Multi-line sequences, for cross-line session state.
pub const sequences = [_][]const []const u8{
    &.{ "const x = 5;", "const y = x * 2;", "y + 1" },
    &.{ "const S = struct { a: u8 };", "@as(S, .{ .a = 3 }).a" },
    &.{ "fn f(n: u32) u32 { return n + 1; }", "f(41)" },
    &.{ "const E = enum { a, b };", "@intFromEnum(E.b)" },
    &.{ "const p: u32 = 5;", "&p", "p + 1" },
    &.{ "fn add(comptime T: type, a: T, b: T) T { return a +% b; }", "add(u8, 200, 100)" },
    &.{ "const S = struct { const k: u8 = 42; };", "S.k" },
    &.{ "const Point = struct { x: i32, y: i32 };", "const origin = Point{ .x = 0, .y = 0 };", "origin.x + origin.y" },
    &.{ "const E = enum(u8) { lo = 1, hi = 255 };", "@intFromEnum(E.hi)" },
};
